---
Name: fromholdio-attributable
---

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.AttributionCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "AttributionCache"
  Psr\SimpleCache\CacheInterface.AttributeFieldSourceCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "AttributeFieldSourceCache"
  Psr\SimpleCache\CacheInterface.AttributableCMSFieldsCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "AttributableCMSFieldsCache"
